namespace: default

deploymentName: myapp3-deploy
serviceName: myapp3-svc

image:
  registry: docker.io
  repository: ngochez95/myapp
  tag: "latest"

ports:
  containerPort: 8082
  nodePort: 30082

replicas: 1

